#!/bin/bash

## Author : Aditya Shakya
## Github : adi1090x

## Amendments: Daniel Einars
## Github : polaroidkidd

# Custom Rofi Script

BORDER="#00acc1"
SEPARATOR="#000000"
FOREGROUND="#00acc1"
BACKGROUND="#000000"
BACKGROUND_ALT="#000000"
HIGHLIGHT_BACKGROUND="#101010"
HIGHLIGHT_FOREGROUND="#00acc1"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"


SDIR="$HOME/.config/polybar/scripts"
